-- Generated seed for plm_item (11 rows).
-- Idempotent: re-running upserts on plm_internal_id.
BEGIN;
INSERT INTO plm_item (plm_internal_id, item_number, family_id, prefix, code, item_name, customer, title, folder, workflow, status, custom_status, priority, end_date, description, print_method, previous_item_no, contents, material_codes, brand_category, product_category, brand, season, design_request, design_brief, image_link, ready_for_wrike, created_at, modified_at) VALUES ('1', 'WP-71511-006-319', 'WP-71511', 'WP', '71511', 'WINNIE-THE-POOH PANCAKE PAN', '*CORE', 'WP-71511 WINNIE-THE-POOH PANCAKE PAN', '', '', 'Active', '', 'Normal', '', '<h5>Design Brief:     </h5>REF WP-68151
ARTWORK REFRESH<br><br><h5>Material Codes:     </h5>WINNIE-THE-POOH PANCAKE PAN (007251MET)<br><h5>Contents:     </h5>- WINNIE THE POOH PAN- PANCAKE MIX, 2.1 OZ', 'MATTE', 'WP-68151', '- WINNIE THE POOH PAN- PANCAKE MIX, 2.1 OZ', 'WINNIE-THE-POOH PANCAKE PAN (007251MET)', 'THOUGHTFULLY GOURMET', 'BAKING', 'WINNIE-THE-POOH', '2026 FALL/HOLIDAY', 'REF WP-68151
ARTWORK REFRESH', '', '', true, '2026-06-04T00:00:00+00:00', '2026-06-04T00:00:00+00:00')
  ON CONFLICT (plm_internal_id) DO UPDATE SET item_number = EXCLUDED.item_number, family_id = EXCLUDED.family_id, prefix = EXCLUDED.prefix, code = EXCLUDED.code, item_name = EXCLUDED.item_name, customer = EXCLUDED.customer, title = EXCLUDED.title, folder = EXCLUDED.folder, workflow = EXCLUDED.workflow, status = EXCLUDED.status, custom_status = EXCLUDED.custom_status, priority = EXCLUDED.priority, end_date = EXCLUDED.end_date, description = EXCLUDED.description, print_method = EXCLUDED.print_method, previous_item_no = EXCLUDED.previous_item_no, contents = EXCLUDED.contents, material_codes = EXCLUDED.material_codes, brand_category = EXCLUDED.brand_category, product_category = EXCLUDED.product_category, brand = EXCLUDED.brand, season = EXCLUDED.season, design_request = EXCLUDED.design_request, design_brief = EXCLUDED.design_brief, image_link = EXCLUDED.image_link, ready_for_wrike = EXCLUDED.ready_for_wrike, created_at = EXCLUDED.created_at, modified_at = EXCLUDED.modified_at;
INSERT INTO plm_item (plm_internal_id, item_number, family_id, prefix, code, item_name, customer, title, folder, workflow, status, custom_status, priority, end_date, description, print_method, previous_item_no, contents, material_codes, brand_category, product_category, brand, season, design_request, design_brief, image_link, ready_for_wrike, created_at, modified_at) VALUES ('2', 'WP-71512-006-319', 'WP-71512', 'WP', '71512', 'WINNIE-THE-POOH DOUBLE WALL MUG TEA SET', '*CORE', 'WP-71512 WINNIE-THE-POOH DOUBLE WALL MUG TEA SET', '', '', 'Active', '', 'Normal', '', '<h5>Design Brief:     </h5>REF WP-70108
ARTWORK REFRESH<br><br><h5>Material Codes:     </h5>GLASS MUG
length 15cm ,width 9cm,height11cm<br><h5>Contents:     </h5>- DOUBLE WALL GLASS MUG, 12.6 OZ- EARL GREY BLACK TEA - 4 - 1 GRAM TEA BAGS IN A FOIL POUCH', 'MATTE', 'WP-70108', '- DOUBLE WALL GLASS MUG, 12.6 OZ- EARL GREY BLACK TEA - 4 - 1 GRAM TEA BAGS IN A FOIL POUCH', 'GLASS MUG
length 15cm ,width 9cm,height11cm', 'THOUGHTFULLY GOURMET', 'HOT DRINKS', 'WINNIE-THE-POOH', '2026 FALL/HOLIDAY', 'REF WP-70108
ARTWORK REFRESH', '', '', true, '2026-06-04T00:00:00+00:00', '2026-06-04T00:00:00+00:00')
  ON CONFLICT (plm_internal_id) DO UPDATE SET item_number = EXCLUDED.item_number, family_id = EXCLUDED.family_id, prefix = EXCLUDED.prefix, code = EXCLUDED.code, item_name = EXCLUDED.item_name, customer = EXCLUDED.customer, title = EXCLUDED.title, folder = EXCLUDED.folder, workflow = EXCLUDED.workflow, status = EXCLUDED.status, custom_status = EXCLUDED.custom_status, priority = EXCLUDED.priority, end_date = EXCLUDED.end_date, description = EXCLUDED.description, print_method = EXCLUDED.print_method, previous_item_no = EXCLUDED.previous_item_no, contents = EXCLUDED.contents, material_codes = EXCLUDED.material_codes, brand_category = EXCLUDED.brand_category, product_category = EXCLUDED.product_category, brand = EXCLUDED.brand, season = EXCLUDED.season, design_request = EXCLUDED.design_request, design_brief = EXCLUDED.design_brief, image_link = EXCLUDED.image_link, ready_for_wrike = EXCLUDED.ready_for_wrike, created_at = EXCLUDED.created_at, modified_at = EXCLUDED.modified_at;
INSERT INTO plm_item (plm_internal_id, item_number, family_id, prefix, code, item_name, customer, title, folder, workflow, status, custom_status, priority, end_date, description, print_method, previous_item_no, contents, material_codes, brand_category, product_category, brand, season, design_request, design_brief, image_link, ready_for_wrike, created_at, modified_at) VALUES ('3', 'WP-71513-006-319', 'WP-71513', 'WP', '71513', 'WINNIE-THE-POOH HOT COCOA AND MUG SET MIXED CASE', '*CORE', 'WP-71513 WINNIE-THE-POOH HOT COCOA AND MUG SET MIXED CASE', '', '', 'Active', '', 'Normal', '', '<h5>Design Brief:     </h5>REF WP-68168
UPDATE MUGS
ARTWORK REFRESH<br><br><h5>Material Codes:     </h5>CERAMIC MUG - 11 OZ - IOWA 	002728CER<br><h5>Contents:     </h5>A - CERAMIC MUG  11 OZ DOUBLE CHOCOLATE COCOA MIX, 1 OZB - CERAMIC MUG  11 OZ   - DOUBLE CHOCOLATE COCOA MIX, 1 OZ', 'MATTE', 'WP-68168', 'A - CERAMIC MUG  11 OZ DOUBLE CHOCOLATE COCOA MIX, 1 OZB - CERAMIC MUG  11 OZ   - DOUBLE CHOCOLATE COCOA MIX, 1 OZ', 'CERAMIC MUG - 11 OZ - IOWA 	002728CER', 'THOUGHTFULLY GOURMET', 'HOT DRINKS', 'WINNIE-THE-POOH', '2026 FALL/HOLIDAY', 'REF WP-68168
UPDATE MUGS
ARTWORK REFRESH', '', '', true, '2026-06-04T00:00:00+00:00', '2026-06-04T00:00:00+00:00')
  ON CONFLICT (plm_internal_id) DO UPDATE SET item_number = EXCLUDED.item_number, family_id = EXCLUDED.family_id, prefix = EXCLUDED.prefix, code = EXCLUDED.code, item_name = EXCLUDED.item_name, customer = EXCLUDED.customer, title = EXCLUDED.title, folder = EXCLUDED.folder, workflow = EXCLUDED.workflow, status = EXCLUDED.status, custom_status = EXCLUDED.custom_status, priority = EXCLUDED.priority, end_date = EXCLUDED.end_date, description = EXCLUDED.description, print_method = EXCLUDED.print_method, previous_item_no = EXCLUDED.previous_item_no, contents = EXCLUDED.contents, material_codes = EXCLUDED.material_codes, brand_category = EXCLUDED.brand_category, product_category = EXCLUDED.product_category, brand = EXCLUDED.brand, season = EXCLUDED.season, design_request = EXCLUDED.design_request, design_brief = EXCLUDED.design_brief, image_link = EXCLUDED.image_link, ready_for_wrike = EXCLUDED.ready_for_wrike, created_at = EXCLUDED.created_at, modified_at = EXCLUDED.modified_at;
INSERT INTO plm_item (plm_internal_id, item_number, family_id, prefix, code, item_name, customer, title, folder, workflow, status, custom_status, priority, end_date, description, print_method, previous_item_no, contents, material_codes, brand_category, product_category, brand, season, design_request, design_brief, image_link, ready_for_wrike, created_at, modified_at) VALUES ('4', 'WP-71514-006-319', 'WP-71514', 'WP', '71514', 'WINNIE-THE-POOH TEA CANISTER 80 CT', '*CORE', 'WP-71514 WINNIE-THE-POOH TEA CANISTER 80 CT', '', '', 'Active', '', 'Normal', '', '<h5>Design Brief:     </h5>REF WP-68170
ARTWORK REFRESH<br><br><h5>Material Codes:     </h5>"MEDIUM TEA TIN (007520MET)
 
(2) EARL GREY BLACK TEA  10  1 GRAM TEA BAGS IN A FOIL POUCH (TAGLESS)
(2) ENGLISH BREAKFAST BLACK TEA  10  1 GRAM TEA BAGS IN A FOIL POUCH (TAGLESS)
FRENCH VANILLA BLACK TEA  10  1 GRAM TEA BAGS IN A FOIL POUCH (TAGLESS)
HONEY HIBISCUS BLACK TEA  10  1 GRAM TEA BAGS IN A FOIL POUCH (TAGLESS)
ORANGE BLACK TEA  10  1 GRAM TEA BAGS IN A FOIL POUCH (TAGLESS) (003962FOO)
BERRY HIBISCUS BLACK TEA  10  1 GRAM TEA BAGS IN A FOIL POUCH (TAGLESS) (007292FOO)"<br><h5>Contents:     </h5>"  METAL TEA TIN
(2) EARL GREY BLACK TEA  10  1 GRAM TEA BAGS IN A FOIL POUCH (TAGLESS)
(2) ENGLISH BREAKFAST BLACK TEA  10  1 GRAM TEA BAGS IN A FOIL POUCH (TAGLESS)
FRENCH VANILLA BLACK TEA  10  1 GRAM TEA BAGS IN A FOIL POUCH (TAGLESS)
HONEY HIBISCUS BLACK TEA  10  1 GRAM TEA BAGS IN A FOIL POUCH (TAGLESS)
ORANGE BLACK TEA  10  1 GRAM TEA BAGS IN A FOIL POUCH (TAGLESS)
BERRY HIBISCUS BLACK TEA  10  1 GRAM TEA BAGS IN A FOIL POUCH (TAGLESS)"', 'MATTE', 'WP-68170', '"  METAL TEA TIN
(2) EARL GREY BLACK TEA  10  1 GRAM TEA BAGS IN A FOIL POUCH (TAGLESS)
(2) ENGLISH BREAKFAST BLACK TEA  10  1 GRAM TEA BAGS IN A FOIL POUCH (TAGLESS)
FRENCH VANILLA BLACK TEA  10  1 GRAM TEA BAGS IN A FOIL POUCH (TAGLESS)
HONEY HIBISCUS BLACK TEA  10  1 GRAM TEA BAGS IN A FOIL POUCH (TAGLESS)
ORANGE BLACK TEA  10  1 GRAM TEA BAGS IN A FOIL POUCH (TAGLESS)
BERRY HIBISCUS BLACK TEA  10  1 GRAM TEA BAGS IN A FOIL POUCH (TAGLESS)"', '"MEDIUM TEA TIN (007520MET)
 
(2) EARL GREY BLACK TEA  10  1 GRAM TEA BAGS IN A FOIL POUCH (TAGLESS)
(2) ENGLISH BREAKFAST BLACK TEA  10  1 GRAM TEA BAGS IN A FOIL POUCH (TAGLESS)
FRENCH VANILLA BLACK TEA  10  1 GRAM TEA BAGS IN A FOIL POUCH (TAGLESS)
HONEY HIBISCUS BLACK TEA  10  1 GRAM TEA BAGS IN A FOIL POUCH (TAGLESS)
ORANGE BLACK TEA  10  1 GRAM TEA BAGS IN A FOIL POUCH (TAGLESS) (003962FOO)
BERRY HIBISCUS BLACK TEA  10  1 GRAM TEA BAGS IN A FOIL POUCH (TAGLESS) (007292FOO)"', 'THOUGHTFULLY GOURMET', 'HOT DRINKS', 'WINNIE-THE-POOH', '2026 FALL/HOLIDAY', 'REF WP-68170
ARTWORK REFRESH', '', '', true, '2026-06-04T00:00:00+00:00', '2026-06-04T00:00:00+00:00')
  ON CONFLICT (plm_internal_id) DO UPDATE SET item_number = EXCLUDED.item_number, family_id = EXCLUDED.family_id, prefix = EXCLUDED.prefix, code = EXCLUDED.code, item_name = EXCLUDED.item_name, customer = EXCLUDED.customer, title = EXCLUDED.title, folder = EXCLUDED.folder, workflow = EXCLUDED.workflow, status = EXCLUDED.status, custom_status = EXCLUDED.custom_status, priority = EXCLUDED.priority, end_date = EXCLUDED.end_date, description = EXCLUDED.description, print_method = EXCLUDED.print_method, previous_item_no = EXCLUDED.previous_item_no, contents = EXCLUDED.contents, material_codes = EXCLUDED.material_codes, brand_category = EXCLUDED.brand_category, product_category = EXCLUDED.product_category, brand = EXCLUDED.brand, season = EXCLUDED.season, design_request = EXCLUDED.design_request, design_brief = EXCLUDED.design_brief, image_link = EXCLUDED.image_link, ready_for_wrike = EXCLUDED.ready_for_wrike, created_at = EXCLUDED.created_at, modified_at = EXCLUDED.modified_at;
INSERT INTO plm_item (plm_internal_id, item_number, family_id, prefix, code, item_name, customer, title, folder, workflow, status, custom_status, priority, end_date, description, print_method, previous_item_no, contents, material_codes, brand_category, product_category, brand, season, design_request, design_brief, image_link, ready_for_wrike, created_at, modified_at) VALUES ('5', 'WP-71515-006-319', 'WP-71515', 'WP', '71515', 'WINNIE-THE-POOH HONEY FLAVORED PANCAKE SYRUPS 4PK', '*CORE', 'WP-71515 WINNIE-THE-POOH HONEY FLAVORED PANCAKE SYRUPS 4PK', '', '', 'Active', '', 'Normal', '', '<h5>Design Brief:     </h5>REF WP-70915
ARTWORK REFRESH<br><br><h5>Material Codes:     </h5>GLASS HEXAGON HONEY JAR 007477GLA
 
MINI WOOD DIPPER 007469WOO
 
PANCAKE SYRUP, HONEY BUTTER, # 9-15- 007685FOO
 
PANCAKE SYRUP, HONEY CINNAMON, # 9-16- 007686FOO
 
PANCAKE SYRUP, HONEY VANILLA, # 9-14- 007684FOO
 
PANCAKE SYRUP, HONEY MAPLE, # 9-17- 007687FOO<br><h5>Contents:     </h5>- MINI WOOD DIPPER4 - 1.5 OZ GLASS JARS WITH;- HONEY BUTTER FLAVORED PANCAKE SYRUP- HONEY CINNAMON FLAVORED PANCAKE SYRUP- HONEY VANILLA FLAVORED PANCAKE SYRUP- HONEY MAPLE FLAVORED PANCAKE SYRUP', 'MATTE', 'WP-70915', '- MINI WOOD DIPPER4 - 1.5 OZ GLASS JARS WITH;- HONEY BUTTER FLAVORED PANCAKE SYRUP- HONEY CINNAMON FLAVORED PANCAKE SYRUP- HONEY VANILLA FLAVORED PANCAKE SYRUP- HONEY MAPLE FLAVORED PANCAKE SYRUP', 'GLASS HEXAGON HONEY JAR 007477GLA
 
MINI WOOD DIPPER 007469WOO
 
PANCAKE SYRUP, HONEY BUTTER, # 9-15- 007685FOO
 
PANCAKE SYRUP, HONEY CINNAMON, # 9-16- 007686FOO
 
PANCAKE SYRUP, HONEY VANILLA, # 9-14- 007684FOO
 
PANCAKE SYRUP, HONEY MAPLE, # 9-17- 007687FOO', 'THOUGHTFULLY GOURMET', 'BAKING', 'WINNIE-THE-POOH', '2026 FALL/HOLIDAY', 'REF WP-70915
ARTWORK REFRESH', '', '', true, '2026-06-04T00:00:00+00:00', '2026-06-04T00:00:00+00:00')
  ON CONFLICT (plm_internal_id) DO UPDATE SET item_number = EXCLUDED.item_number, family_id = EXCLUDED.family_id, prefix = EXCLUDED.prefix, code = EXCLUDED.code, item_name = EXCLUDED.item_name, customer = EXCLUDED.customer, title = EXCLUDED.title, folder = EXCLUDED.folder, workflow = EXCLUDED.workflow, status = EXCLUDED.status, custom_status = EXCLUDED.custom_status, priority = EXCLUDED.priority, end_date = EXCLUDED.end_date, description = EXCLUDED.description, print_method = EXCLUDED.print_method, previous_item_no = EXCLUDED.previous_item_no, contents = EXCLUDED.contents, material_codes = EXCLUDED.material_codes, brand_category = EXCLUDED.brand_category, product_category = EXCLUDED.product_category, brand = EXCLUDED.brand, season = EXCLUDED.season, design_request = EXCLUDED.design_request, design_brief = EXCLUDED.design_brief, image_link = EXCLUDED.image_link, ready_for_wrike = EXCLUDED.ready_for_wrike, created_at = EXCLUDED.created_at, modified_at = EXCLUDED.modified_at;
INSERT INTO plm_item (plm_internal_id, item_number, family_id, prefix, code, item_name, customer, title, folder, workflow, status, custom_status, priority, end_date, description, print_method, previous_item_no, contents, material_codes, brand_category, product_category, brand, season, design_request, design_brief, image_link, ready_for_wrike, created_at, modified_at) VALUES ('6', 'WP-71516-006-319', 'WP-71516', 'WP', '71516', 'WINNIE-THE-POOH MUG AND TEA FLIGHT SET', '*CORE', 'WP-71516 WINNIE-THE-POOH MUG AND TEA FLIGHT SET', '', '', 'Active', '', 'Normal', '', '<h5>Design Brief:     </h5>REF WP-70663
ARTWORK REFRESH<br><br><h5>Material Codes:     </h5>DOUBLE WALL GLASS MUGS NEW<br><h5>Contents:     </h5>- DOUBLE WALL GLASS MUG, 12.6 OZ- EARL GREY BLACK TEA - 4 - 1 GRAM TEA BAGS IN A FOIL POUCH - ENGLISH BREAKFAST BLACK TEA - 4 - 1 GRAM TEA BAGS IN A FOIL POUCH - FRENCH VANILLA  BLACK TEA - 4 - 1 GRAM TEA BAGS IN A FOIL POUCH - APPLE CINNAMON BLACK TEA - 4 - 1 GRAM TEA BAGS IN A FOIL POUCH', 'MATTE', 'WP-70663', '- DOUBLE WALL GLASS MUG, 12.6 OZ- EARL GREY BLACK TEA - 4 - 1 GRAM TEA BAGS IN A FOIL POUCH - ENGLISH BREAKFAST BLACK TEA - 4 - 1 GRAM TEA BAGS IN A FOIL POUCH - FRENCH VANILLA  BLACK TEA - 4 - 1 GRAM TEA BAGS IN A FOIL POUCH - APPLE CINNAMON BLACK TEA - 4 - 1 GRAM TEA BAGS IN A FOIL POUCH', 'DOUBLE WALL GLASS MUGS NEW', 'THOUGHTFULLY GOURMET', 'HOT DRINKS', 'WINNIE-THE-POOH', '2026 FALL/HOLIDAY', 'REF WP-70663
ARTWORK REFRESH', '', '', true, '2026-06-04T00:00:00+00:00', '2026-06-04T00:00:00+00:00')
  ON CONFLICT (plm_internal_id) DO UPDATE SET item_number = EXCLUDED.item_number, family_id = EXCLUDED.family_id, prefix = EXCLUDED.prefix, code = EXCLUDED.code, item_name = EXCLUDED.item_name, customer = EXCLUDED.customer, title = EXCLUDED.title, folder = EXCLUDED.folder, workflow = EXCLUDED.workflow, status = EXCLUDED.status, custom_status = EXCLUDED.custom_status, priority = EXCLUDED.priority, end_date = EXCLUDED.end_date, description = EXCLUDED.description, print_method = EXCLUDED.print_method, previous_item_no = EXCLUDED.previous_item_no, contents = EXCLUDED.contents, material_codes = EXCLUDED.material_codes, brand_category = EXCLUDED.brand_category, product_category = EXCLUDED.product_category, brand = EXCLUDED.brand, season = EXCLUDED.season, design_request = EXCLUDED.design_request, design_brief = EXCLUDED.design_brief, image_link = EXCLUDED.image_link, ready_for_wrike = EXCLUDED.ready_for_wrike, created_at = EXCLUDED.created_at, modified_at = EXCLUDED.modified_at;
INSERT INTO plm_item (plm_internal_id, item_number, family_id, prefix, code, item_name, customer, title, folder, workflow, status, custom_status, priority, end_date, description, print_method, previous_item_no, contents, material_codes, brand_category, product_category, brand, season, design_request, design_brief, image_link, ready_for_wrike, created_at, modified_at) VALUES ('7', 'LT-68102-006-319', 'LT-68102', 'LT', '68102', 'LINDT LINDOR MILK CHOCOLATE TRUFFLES', '*CORE', 'LT-68102 LINDT LINDOR MILK CHOCOLATE TRUFFLES', '', '', 'Active', '', 'Normal', '', '<h5>Design Brief:     </h5>REF LT-67101<br><h5>Material Codes:     </h5>008801FOO LINDOR MILK CHOCOLATE TRUFFLES<br><h5>Contents:     </h5>- LINDOR MILK CHOCOLATE TRUFFLES, 8.5 OZ', 'MATTE', 'LT-67101', '- LINDOR MILK CHOCOLATE TRUFFLES, 8.5 OZ', '008801FOO LINDOR MILK CHOCOLATE TRUFFLES', 'THOUGHTFULLY GOURMET', 'CONFECTION', 'LINDT', '2026 FALL/HOLIDAY', 'REF LT-67101 ARTWORK REFRESH', '', '', true, '2026-06-04T00:00:00+00:00', '2026-06-04T00:00:00+00:00')
  ON CONFLICT (plm_internal_id) DO UPDATE SET item_number = EXCLUDED.item_number, family_id = EXCLUDED.family_id, prefix = EXCLUDED.prefix, code = EXCLUDED.code, item_name = EXCLUDED.item_name, customer = EXCLUDED.customer, title = EXCLUDED.title, folder = EXCLUDED.folder, workflow = EXCLUDED.workflow, status = EXCLUDED.status, custom_status = EXCLUDED.custom_status, priority = EXCLUDED.priority, end_date = EXCLUDED.end_date, description = EXCLUDED.description, print_method = EXCLUDED.print_method, previous_item_no = EXCLUDED.previous_item_no, contents = EXCLUDED.contents, material_codes = EXCLUDED.material_codes, brand_category = EXCLUDED.brand_category, product_category = EXCLUDED.product_category, brand = EXCLUDED.brand, season = EXCLUDED.season, design_request = EXCLUDED.design_request, design_brief = EXCLUDED.design_brief, image_link = EXCLUDED.image_link, ready_for_wrike = EXCLUDED.ready_for_wrike, created_at = EXCLUDED.created_at, modified_at = EXCLUDED.modified_at;
INSERT INTO plm_item (plm_internal_id, item_number, family_id, prefix, code, item_name, customer, title, folder, workflow, status, custom_status, priority, end_date, description, print_method, previous_item_no, contents, material_codes, brand_category, product_category, brand, season, design_request, design_brief, image_link, ready_for_wrike, created_at, modified_at) VALUES ('8', 'LT-68103-006-319', 'LT-68103', 'LT', '68103', 'LINDT EXCELLENCE 70% DARK CHOCOLATE BAR', '*CORE', 'LT-68103 LINDT EXCELLENCE 70% DARK CHOCOLATE BAR', '', '', 'Active', '', 'Normal', '', '<h5>Design Brief:     </h5>REF LT-67102<br><h5>Material Codes:     </h5>008802FOO EXCELLENCE 70% DARK CHOCOLATE', 'MATTE', 'LT-67102', '- DARK CHOCOLATE BAR, 70% CACAO, 3.5 OZ', '008802FOO EXCELLENCE 70% DARK CHOCOLATE', 'THOUGHTFULLY GOURMET', 'CONFECTION', 'LINDT', '2026 FALL/HOLIDAY', 'REF LT-67102 ARTWORK REFRESH', '', '', true, '2026-06-04T00:00:00+00:00', '2026-06-04T00:00:00+00:00')
  ON CONFLICT (plm_internal_id) DO UPDATE SET item_number = EXCLUDED.item_number, family_id = EXCLUDED.family_id, prefix = EXCLUDED.prefix, code = EXCLUDED.code, item_name = EXCLUDED.item_name, customer = EXCLUDED.customer, title = EXCLUDED.title, folder = EXCLUDED.folder, workflow = EXCLUDED.workflow, status = EXCLUDED.status, custom_status = EXCLUDED.custom_status, priority = EXCLUDED.priority, end_date = EXCLUDED.end_date, description = EXCLUDED.description, print_method = EXCLUDED.print_method, previous_item_no = EXCLUDED.previous_item_no, contents = EXCLUDED.contents, material_codes = EXCLUDED.material_codes, brand_category = EXCLUDED.brand_category, product_category = EXCLUDED.product_category, brand = EXCLUDED.brand, season = EXCLUDED.season, design_request = EXCLUDED.design_request, design_brief = EXCLUDED.design_brief, image_link = EXCLUDED.image_link, ready_for_wrike = EXCLUDED.ready_for_wrike, created_at = EXCLUDED.created_at, modified_at = EXCLUDED.modified_at;
INSERT INTO plm_item (plm_internal_id, item_number, family_id, prefix, code, item_name, customer, title, folder, workflow, status, custom_status, priority, end_date, description, print_method, previous_item_no, contents, material_codes, brand_category, product_category, brand, season, design_request, design_brief, image_link, ready_for_wrike, created_at, modified_at) VALUES ('9', 'LT-68104-006-319', 'LT-68104', 'LT', '68104', 'LINDT LINDOR ASSORTED CHOCOLATE TRUFFLES', '*CORE', 'LT-68104 LINDT LINDOR ASSORTED CHOCOLATE TRUFFLES', '', '', 'Active', '', 'Normal', '', '<h5>Design Brief:     </h5>REF LT-67103<br><h5>Material Codes:     </h5>008803FOO LINDOR ASSORTED TRUFFLES', 'MATTE', 'LT-67103', '- ASSORTED CHOCOLATE TRUFFLES, 15.2 OZ', '008803FOO LINDOR ASSORTED TRUFFLES', 'THOUGHTFULLY GOURMET', 'CONFECTION', 'LINDT', '2026 FALL/HOLIDAY', 'REF LT-67103 ARTWORK REFRESH', '', '', true, '2026-06-04T00:00:00+00:00', '2026-06-04T00:00:00+00:00')
  ON CONFLICT (plm_internal_id) DO UPDATE SET item_number = EXCLUDED.item_number, family_id = EXCLUDED.family_id, prefix = EXCLUDED.prefix, code = EXCLUDED.code, item_name = EXCLUDED.item_name, customer = EXCLUDED.customer, title = EXCLUDED.title, folder = EXCLUDED.folder, workflow = EXCLUDED.workflow, status = EXCLUDED.status, custom_status = EXCLUDED.custom_status, priority = EXCLUDED.priority, end_date = EXCLUDED.end_date, description = EXCLUDED.description, print_method = EXCLUDED.print_method, previous_item_no = EXCLUDED.previous_item_no, contents = EXCLUDED.contents, material_codes = EXCLUDED.material_codes, brand_category = EXCLUDED.brand_category, product_category = EXCLUDED.product_category, brand = EXCLUDED.brand, season = EXCLUDED.season, design_request = EXCLUDED.design_request, design_brief = EXCLUDED.design_brief, image_link = EXCLUDED.image_link, ready_for_wrike = EXCLUDED.ready_for_wrike, created_at = EXCLUDED.created_at, modified_at = EXCLUDED.modified_at;
INSERT INTO plm_item (plm_internal_id, item_number, family_id, prefix, code, item_name, customer, title, folder, workflow, status, custom_status, priority, end_date, description, print_method, previous_item_no, contents, material_codes, brand_category, product_category, brand, season, design_request, design_brief, image_link, ready_for_wrike, created_at, modified_at) VALUES ('10', 'LT-68105-006-319', 'LT-68105', 'LT', '68105', 'LINDT GOLD BUNNY MILK CHOCOLATE', '*CORE', 'LT-68105 LINDT GOLD BUNNY MILK CHOCOLATE', '', '', 'Active', '', 'Normal', '', '<h5>Design Brief:     </h5>REF LT-67104<br><h5>Material Codes:     </h5>008804FOO GOLD BUNNY MILK CHOCOLATE', 'MATTE', 'LT-67104', '- MILK CHOCOLATE GOLD BUNNY, 3.5 OZ', '008804FOO GOLD BUNNY MILK CHOCOLATE', 'THOUGHTFULLY GOURMET', 'CONFECTION', 'LINDT', '2026 FALL/HOLIDAY', 'REF LT-67104 ARTWORK REFRESH', '', '', true, '2026-06-04T00:00:00+00:00', '2026-06-04T00:00:00+00:00')
  ON CONFLICT (plm_internal_id) DO UPDATE SET item_number = EXCLUDED.item_number, family_id = EXCLUDED.family_id, prefix = EXCLUDED.prefix, code = EXCLUDED.code, item_name = EXCLUDED.item_name, customer = EXCLUDED.customer, title = EXCLUDED.title, folder = EXCLUDED.folder, workflow = EXCLUDED.workflow, status = EXCLUDED.status, custom_status = EXCLUDED.custom_status, priority = EXCLUDED.priority, end_date = EXCLUDED.end_date, description = EXCLUDED.description, print_method = EXCLUDED.print_method, previous_item_no = EXCLUDED.previous_item_no, contents = EXCLUDED.contents, material_codes = EXCLUDED.material_codes, brand_category = EXCLUDED.brand_category, product_category = EXCLUDED.product_category, brand = EXCLUDED.brand, season = EXCLUDED.season, design_request = EXCLUDED.design_request, design_brief = EXCLUDED.design_brief, image_link = EXCLUDED.image_link, ready_for_wrike = EXCLUDED.ready_for_wrike, created_at = EXCLUDED.created_at, modified_at = EXCLUDED.modified_at;
INSERT INTO plm_item (plm_internal_id, item_number, family_id, prefix, code, item_name, customer, title, folder, workflow, status, custom_status, priority, end_date, description, print_method, previous_item_no, contents, material_codes, brand_category, product_category, brand, season, design_request, design_brief, image_link, ready_for_wrike, created_at, modified_at) VALUES ('11', 'LT-68106-006-319', 'LT-68106', 'LT', '68106', 'LINDT HELLO STRAWBERRY AND CREAM CHOCOLATE BAR', '*CORE', 'LT-68106 LINDT HELLO STRAWBERRY AND CREAM CHOCOLATE BAR', '', '', 'Active', '', 'Normal', '', '<h5>Design Brief:     </h5>REF LT-67105<br><h5>Material Codes:     </h5>008805FOO HELLO STRAWBERRY CREAM BAR', 'MATTE', 'LT-67105', '- STRAWBERRY AND CREAM CHOCOLATE BAR, 3.1 OZ', '008805FOO HELLO STRAWBERRY CREAM BAR', 'THOUGHTFULLY GOURMET', 'CONFECTION', 'LINDT', '2026 FALL/HOLIDAY', 'REF LT-67105 ARTWORK REFRESH', '', '', true, '2026-06-04T00:00:00+00:00', '2026-06-04T00:00:00+00:00')
  ON CONFLICT (plm_internal_id) DO UPDATE SET item_number = EXCLUDED.item_number, family_id = EXCLUDED.family_id, prefix = EXCLUDED.prefix, code = EXCLUDED.code, item_name = EXCLUDED.item_name, customer = EXCLUDED.customer, title = EXCLUDED.title, folder = EXCLUDED.folder, workflow = EXCLUDED.workflow, status = EXCLUDED.status, custom_status = EXCLUDED.custom_status, priority = EXCLUDED.priority, end_date = EXCLUDED.end_date, description = EXCLUDED.description, print_method = EXCLUDED.print_method, previous_item_no = EXCLUDED.previous_item_no, contents = EXCLUDED.contents, material_codes = EXCLUDED.material_codes, brand_category = EXCLUDED.brand_category, product_category = EXCLUDED.product_category, brand = EXCLUDED.brand, season = EXCLUDED.season, design_request = EXCLUDED.design_request, design_brief = EXCLUDED.design_brief, image_link = EXCLUDED.image_link, ready_for_wrike = EXCLUDED.ready_for_wrike, created_at = EXCLUDED.created_at, modified_at = EXCLUDED.modified_at;
COMMIT;
-- end (11 rows)
